name : Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo chmod 777 /var/run/docker.sock
            cd /home/kamarrs/BackEnd
            sudo git pull origin main
            sudo docker build -t kamar-rs-images:latest .
            sudo docker run -d -p 80:8080 -e SERVER_PORT=${{ secrets.SERVER_PORT }} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e AWS_REGION=${{ secrets.AWS_REGION }} -e AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} -e ACCESS_KEY_IAM=${{ secrets.ACCESS_KEY_IAM }} -e SECRET_KEY_IAM=${{ secrets.SECRET_KEY_IAM }} -e SECRET_JWT=${{ secrets.SECRET_JWT }} -e MIDTRANS_SERVER_KEY=${{ secrets.MIDTRANS_SERVER_KEY }} -e GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }} -e GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }} -e MIDTRANS_CLIENT_KEY=${{ secrets.MIDTRANS_CLIENT_KEY }} -e MIDTRANS_MERCHANT_ID=${{ secrets.MIDTRANS_MERCHANT_ID }} -e EMAIL_FROM=${{ secrets.EMAIL_FROM }} -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} -e GOOGLE_OAUTH_CLIENT_ID1=${{ secrets.GOOGLE_OAUTH_CLIENT_ID1 }} -e GOOGLE_OAUTH_CLIENT_SECRET1=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET1 }} -e GOOGLE_PROJECT_ID1=${{ secrets.GOOGLE_PROJECT_ID1 }} --name kamarRSContainer kamar-rs-images:latest
